# include <iostream>
using namespace std;

int main() {
        cout << "hhqhx";
        cout << "bxfky";
        cout << "ebvwq";
        cout << "novmb";
        cout << "bmswj";
        cout << "iignn";
        cout << "kvobg";
        cout << "lqhhm";
        cout << "njymh";
        cout << "efwpc";
        cout << "kmtbo";
        cout << "vigal";
        cout << "oqcof";
        cout << "psbax";
        cout << "nikpv";
        cout << "ekgdn";
        cout << "ekmcc";
        cout << "kweig";
        cout << "fkofh";
        cout << "enitt";
        cout << "iinhb";
        cout << "aeekp";
        cout << "xgfmv";
        cout << "sefwh";
        cout << "fsigq";
        cout << "lvjgc";
        cout << "dbyiv";
        cout << "lrkly";
        cout << "bigpg";
        cout << "fogkx";
        cout << "jqbcq";
        cout << "dsxpy";
        cout << "awvsv";
        cout << "mcpxy";
        cout << "ytkth";
        cout << "enhtk";
return 0;
}
